CREATE DATABASE SysmexReferralDB;
GO

USE SysmexReferralDB;
GO

CREATE TABLE Department (
depID TINYINT PRIMARY KEY,
depName VARCHAR(30)
);
GO

CREATE TABLE Surgeon (
surgID SMALLINT PRIMARY KEY,
surgFirstName VARCHAR(30),
surgLastName VARCHAR(35),
depID TINYINT FOREIGN KEY REFERENCES Department(depID)
);
GO

CREATE TABLE Referrer (
refID SMALLINT PRIMARY KEY,
refFirstName VARCHAR(30),
refLastName VARCHAR(35),
refType VARCHAR(20)
);
GO

CREATE TABLE Patient (
patNHI VARCHAR(7) PRIMARY KEY,
patFirstName VARCHAR(30),
patLastName VARCHAR(35),
patDOB DATE,
patGender VARCHAR(1)
);
GO

CREATE TABLE Referral (
referralID SMALLINT PRIMARY KEY,
refDate DATE,
refID SMALLINT FOREIGN KEY REFERENCES Referrer(refID),
patNHI VARCHAR(7) FOREIGN KEY REFERENCES Patient(patNHI),
surgID SMALLINT FOREIGN KEY REFERENCES Surgeon(surgID),
FSA DATE,
eligible BIT
);
GO

CREATE TABLE ReferralError (
refErrorID SMALLINT PRIMARY KEY,
refDate DATE,
refID SMALLINT FOREIGN KEY REFERENCES Referrer(refID),
patNHI VARCHAR(7) FOREIGN KEY REFERENCES Patient(patNHI),
surgID SMALLINT FOREIGN KEY REFERENCES Surgeon(surgID),
FSA DATE,
eligible BIT
);
GO

CREATE TABLE ErrorType (
errorTypeID TINYINT PRIMARY KEY,
errorType VARCHAR(15)
);
GO

CREATE TABLE ReferralError_ErrorType (
errorID SMALLINT PRIMARY KEY,
refErrorID SMALLINT FOREIGN KEY REFERENCES ReferralError(refErrorID),
errorTypeID TINYINT FOREIGN KEY REFERENCES ErrorType(errorTypeID),
errorDate SMALLDATETIME
);
GO