CREATE DATABASE SysmexReferralDB;
GO

USE SysmexReferralDB;
GO

CREATE TABLE Department (
depID TINYINT PRIMARY KEY,
depName VARCHAR(30) NOT NULL
);
GO

CREATE TABLE Surgeon (
surgID SMALLINT PRIMARY KEY,
surgFirstName VARCHAR(30) NOT NULL,
surgLastName VARCHAR(35) NOT NULL,
depID TINYINT FOREIGN KEY REFERENCES Department(depID) NOT NULL
);
GO

CREATE TABLE Referrer (
refID SMALLINT PRIMARY KEY,
refFirstName VARCHAR(30) NOT NULL,
refLastName VARCHAR(35) NOT NULL,
refType VARCHAR(20) NOT NULL
);
GO

CREATE TABLE Patient (
patNHI VARCHAR(7) PRIMARY KEY NOT NULL,
patFirstName VARCHAR(30) NOT NULL,
patLastName VARCHAR(35) NOT NULL,
patDOB DATE NOT NULL,
patGender VARCHAR(1) NOT NULL
);
GO

CREATE TABLE Referral (
referralID SMALLINT PRIMARY KEY,
refDate DATE NOT NULL,
refID SMALLINT FOREIGN KEY REFERENCES Referrer(refID) NOT NULL,
patNHI VARCHAR(7) FOREIGN KEY REFERENCES Patient(patNHI) NOT NULL,
surgID SMALLINT FOREIGN KEY REFERENCES Surgeon(surgID) NOT NULL,
FSA DATE NOT NULL,
eligible BIT
);
GO

CREATE TABLE ReferralError (
refErrorID SMALLINT PRIMARY KEY,
refDate DATE,
refID SMALLINT FOREIGN KEY REFERENCES Referrer(refID),
patNHI VARCHAR(7) FOREIGN KEY REFERENCES Patient(patNHI),
surgID SMALLINT FOREIGN KEY REFERENCES Surgeon(surgID),
FSA DATE,
eligible BIT
);
GO

CREATE TABLE ErrorType (
errorTypeID TINYINT PRIMARY KEY,
errorType VARCHAR(15) NOT NULL
);
GO

CREATE TABLE ReferralError_ErrorType (
errorID SMALLINT PRIMARY KEY,
refErrorID SMALLINT FOREIGN KEY REFERENCES ReferralError(refErrorID) NOT NULL,
errorTypeID TINYINT FOREIGN KEY REFERENCES ErrorType(errorTypeID) NOT NULL,
errorDate SMALLDATETIME NOT NULL
);
GO